# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cq/v1/api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cq/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cq.v1 import knowledge_unit_pb2 as cq_dot_v1_dot_knowledge__unit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63q/v1/api.proto\x12\x05\x63q.v1\x1a\x1a\x63q/v1/knowledge_unit.proto\"v\n\x0eProposeRequest\x12\x0e\n\x06\x64omain\x18\x01 \x03(\t\x12\x1f\n\x07insight\x18\x02 \x01(\x0b\x32\x0e.cq.v1.Insight\x12\x1f\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\x0e.cq.v1.Context\x12\x12\n\ncreated_by\x18\x04 \x01(\t\"?\n\x0fProposeResponse\x12,\n\x0eknowledge_unit\x18\x01 \x01(\x0b\x32\x14.cq.v1.KnowledgeUnit\"R\n\x0cQueryRequest\x12\x0e\n\x06\x64omain\x18\x01 \x03(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x11\n\tframework\x18\x03 \x01(\t\x12\r\n\x05limit\x18\x04 \x01(\x05\"4\n\rQueryResponse\x12#\n\x05units\x18\x01 \x03(\x0b\x32\x14.cq.v1.KnowledgeUnit\"!\n\x0e\x43onfirmRequest\x12\x0f\n\x07unit_id\x18\x01 \x01(\t\"?\n\x0f\x43onfirmResponse\x12,\n\x0eknowledge_unit\x18\x01 \x01(\x0b\x32\x14.cq.v1.KnowledgeUnit\"A\n\x0b\x46lagRequest\x12\x0f\n\x07unit_id\x18\x01 \x01(\t\x12!\n\x06reason\x18\x02 \x01(\x0e\x32\x11.cq.v1.FlagReason\"<\n\x0c\x46lagResponse\x12,\n\x0eknowledge_unit\x18\x01 \x01(\x0b\x32\x14.cq.v1.KnowledgeUnit\"\x0e\n\x0cStatsRequest\"\x88\x01\n\rStatsResponse\x12\x13\n\x0btotal_units\x18\x01 \x01(\x05\x12\x32\n\x07\x64omains\x18\x02 \x03(\x0b\x32!.cq.v1.StatsResponse.DomainsEntry\x1a.\n\x0c\x44omainsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xd4\x02\n\x0eTeamAPIService\x12\x35\n\x06Health\x12\x14.cq.v1.HealthRequest\x1a\x15.cq.v1.HealthResponse\x12\x32\n\x05Query\x12\x13.cq.v1.QueryRequest\x1a\x14.cq.v1.QueryResponse\x12\x38\n\x07Propose\x12\x15.cq.v1.ProposeRequest\x1a\x16.cq.v1.ProposeResponse\x12\x38\n\x07\x43onfirm\x12\x15.cq.v1.ConfirmRequest\x1a\x16.cq.v1.ConfirmResponse\x12/\n\x04\x46lag\x12\x12.cq.v1.FlagRequest\x1a\x13.cq.v1.FlagResponse\x12\x32\n\x05Stats\x12\x13.cq.v1.StatsRequest\x1a\x14.cq.v1.StatsResponseB*Z(github.com/mozilla-ai/cq-proto/cqpb;cqpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cq.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/mozilla-ai/cq-proto/cqpb;cqpb'
  _globals['_STATSRESPONSE_DOMAINSENTRY']._loaded_options = None
  _globals['_STATSRESPONSE_DOMAINSENTRY']._serialized_options = b'8\001'
  _globals['_PROPOSEREQUEST']._serialized_start=54
  _globals['_PROPOSEREQUEST']._serialized_end=172
  _globals['_PROPOSERESPONSE']._serialized_start=174
  _globals['_PROPOSERESPONSE']._serialized_end=237
  _globals['_QUERYREQUEST']._serialized_start=239
  _globals['_QUERYREQUEST']._serialized_end=321
  _globals['_QUERYRESPONSE']._serialized_start=323
  _globals['_QUERYRESPONSE']._serialized_end=375
  _globals['_CONFIRMREQUEST']._serialized_start=377
  _globals['_CONFIRMREQUEST']._serialized_end=410
  _globals['_CONFIRMRESPONSE']._serialized_start=412
  _globals['_CONFIRMRESPONSE']._serialized_end=475
  _globals['_FLAGREQUEST']._serialized_start=477
  _globals['_FLAGREQUEST']._serialized_end=542
  _globals['_FLAGRESPONSE']._serialized_start=544
  _globals['_FLAGRESPONSE']._serialized_end=604
  _globals['_STATSREQUEST']._serialized_start=606
  _globals['_STATSREQUEST']._serialized_end=620
  _globals['_STATSRESPONSE']._serialized_start=623
  _globals['_STATSRESPONSE']._serialized_end=759
  _globals['_STATSRESPONSE_DOMAINSENTRY']._serialized_start=713
  _globals['_STATSRESPONSE_DOMAINSENTRY']._serialized_end=759
  _globals['_HEALTHREQUEST']._serialized_start=761
  _globals['_HEALTHREQUEST']._serialized_end=776
  _globals['_HEALTHRESPONSE']._serialized_start=778
  _globals['_HEALTHRESPONSE']._serialized_end=810
  _globals['_TEAMAPISERVICE']._serialized_start=813
  _globals['_TEAMAPISERVICE']._serialized_end=1153
# @@protoc_insertion_point(module_scope)
