# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cq/v1/knowledge_unit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cq/v1/knowledge_unit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63q/v1/knowledge_unit.proto\x12\x05\x63q.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n\x04\x46lag\x12!\n\x06reason\x18\x01 \x01(\x0e\x32\x11.cq.v1.FlagReason\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\":\n\x07Insight\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\"A\n\x07\x43ontext\x12\x11\n\tlanguages\x18\x01 \x03(\t\x12\x12\n\nframeworks\x18\x02 \x03(\t\x12\x0f\n\x07pattern\x18\x03 \x01(\t\"\x9d\x01\n\x08\x45vidence\x12\x12\n\nconfidence\x18\x01 \x01(\x01\x12\x15\n\rconfirmations\x18\x02 \x01(\x05\x12\x32\n\x0e\x66irst_observed\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0elast_confirmed\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x83\x02\n\rKnowledgeUnit\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x0e\n\x06\x64omain\x18\x03 \x03(\t\x12\x1f\n\x07insight\x18\x04 \x01(\x0b\x32\x0e.cq.v1.Insight\x12\x1f\n\x07\x63ontext\x18\x05 \x01(\x0b\x32\x0e.cq.v1.Context\x12!\n\x08\x65vidence\x18\x06 \x01(\x0b\x32\x0f.cq.v1.Evidence\x12\x19\n\x04tier\x18\x07 \x01(\x0e\x32\x0b.cq.v1.Tier\x12\x12\n\ncreated_by\x18\x08 \x01(\t\x12\x15\n\rsuperseded_by\x18\t \x01(\t\x12\x1a\n\x05\x66lags\x18\n \x03(\x0b\x32\x0b.cq.v1.Flag*O\n\x04Tier\x12\x14\n\x10TIER_UNSPECIFIED\x10\x00\x12\x0e\n\nTIER_LOCAL\x10\x01\x12\x10\n\x0cTIER_PRIVATE\x10\x02\x12\x0f\n\x0bTIER_PUBLIC\x10\x03*v\n\nFlagReason\x12\x1b\n\x17\x46LAG_REASON_UNSPECIFIED\x10\x00\x12\x15\n\x11\x46LAG_REASON_STALE\x10\x01\x12\x19\n\x15\x46LAG_REASON_INCORRECT\x10\x02\x12\x19\n\x15\x46LAG_REASON_DUPLICATE\x10\x03\x42*Z(github.com/mozilla-ai/cq-proto/cqpb;cqpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cq.v1.knowledge_unit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/mozilla-ai/cq-proto/cqpb;cqpb'
  _globals['_TIER']._serialized_start=709
  _globals['_TIER']._serialized_end=788
  _globals['_FLAGREASON']._serialized_start=790
  _globals['_FLAGREASON']._serialized_end=908
  _globals['_FLAG']._serialized_start=70
  _globals['_FLAG']._serialized_end=158
  _globals['_INSIGHT']._serialized_start=160
  _globals['_INSIGHT']._serialized_end=218
  _globals['_CONTEXT']._serialized_start=220
  _globals['_CONTEXT']._serialized_end=285
  _globals['_EVIDENCE']._serialized_start=288
  _globals['_EVIDENCE']._serialized_end=445
  _globals['_KNOWLEDGEUNIT']._serialized_start=448
  _globals['_KNOWLEDGEUNIT']._serialized_end=707
# @@protoc_insertion_point(module_scope)
