# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cq/v1/scoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cq/v1/scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63q/v1/scoring.proto\x12\x05\x63q.v1\"\\\n\x10RelevanceWeights\x12\x15\n\rdomain_weight\x18\x01 \x01(\x01\x12\x17\n\x0flanguage_weight\x18\x02 \x01(\x01\x12\x18\n\x10\x66ramework_weight\x18\x03 \x01(\x01\"\x83\x01\n\x13\x43onfidenceConstants\x12\x1a\n\x12initial_confidence\x18\x01 \x01(\x01\x12\x1a\n\x12\x63onfirmation_boost\x18\x02 \x01(\x01\x12\x14\n\x0c\x66lag_penalty\x18\x03 \x01(\x01\x12\x0f\n\x07\x63\x65iling\x18\x04 \x01(\x01\x12\r\n\x05\x66loor\x18\x05 \x01(\x01\x42*Z(github.com/mozilla-ai/cq-proto/cqpb;cqpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cq.v1.scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/mozilla-ai/cq-proto/cqpb;cqpb'
  _globals['_RELEVANCEWEIGHTS']._serialized_start=30
  _globals['_RELEVANCEWEIGHTS']._serialized_end=122
  _globals['_CONFIDENCECONSTANTS']._serialized_start=125
  _globals['_CONFIDENCECONSTANTS']._serialized_end=256
# @@protoc_insertion_point(module_scope)
